[Service]
PIDFile=
PIDFile=/run/nginx.pid
ExecStartPre=
ExecStartPre=/usr/local/openresty/bin/openresty -t -q -c /etc/nginx/nginx.conf
ExecStart=
ExecStart=/usr/local/openresty/bin/openresty -c /etc/nginx/nginx.conf -g 'daemon on; master_process on;'
ExecReload=
ExecReload=/usr/local/openresty/bin/openresty -c /etc/nginx/nginx.conf -g 'daemon on; master_process on;' -s reload
ExecStop=
ExecStop=-/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid
