[Service]
Environment="RAZORPAY_KEY_ID=rzp_test_SgSmyHctU9PoWi"
Environment="RAZORPAY_KEY_SECRET=ETwDQrescysyjPeBc3pdbCma"
Environment="RAZORPAY_WEBHOOK_SECRET=ETwDQrescysyjPeBc3pdbCma"
Environment="PAY_DOMAIN=pay.autoispbilling.com"
Environment="MAIN_LOGIN_URL=https://www.autoispbilling.com/login"
